// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/proto/v2/room.proto

package protov2connect

import (
	context "context"
	errors "errors"
	v2 "github.com/21hack02win/nascalay-v2/pkg/bufgen/api/proto/v2"
	connect_go "github.com/bufbuild/connect-go"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// RoomServiceName is the fully-qualified name of the RoomService service.
	RoomServiceName = "api.proto.v2.RoomService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RoomServiceCreateProcedure is the fully-qualified name of the RoomService's Create RPC.
	RoomServiceCreateProcedure = "/api.proto.v2.RoomService/Create"
)

// RoomServiceClient is a client for the api.proto.v2.RoomService service.
type RoomServiceClient interface {
	Create(context.Context, *connect_go.Request[v2.RoomServiceCreateRequest]) (*connect_go.Response[v2.RoomServiceCreateResponse], error)
}

// NewRoomServiceClient constructs a client for the api.proto.v2.RoomService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRoomServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) RoomServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &roomServiceClient{
		create: connect_go.NewClient[v2.RoomServiceCreateRequest, v2.RoomServiceCreateResponse](
			httpClient,
			baseURL+RoomServiceCreateProcedure,
			opts...,
		),
	}
}

// roomServiceClient implements RoomServiceClient.
type roomServiceClient struct {
	create *connect_go.Client[v2.RoomServiceCreateRequest, v2.RoomServiceCreateResponse]
}

// Create calls api.proto.v2.RoomService.Create.
func (c *roomServiceClient) Create(ctx context.Context, req *connect_go.Request[v2.RoomServiceCreateRequest]) (*connect_go.Response[v2.RoomServiceCreateResponse], error) {
	return c.create.CallUnary(ctx, req)
}

// RoomServiceHandler is an implementation of the api.proto.v2.RoomService service.
type RoomServiceHandler interface {
	Create(context.Context, *connect_go.Request[v2.RoomServiceCreateRequest]) (*connect_go.Response[v2.RoomServiceCreateResponse], error)
}

// NewRoomServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRoomServiceHandler(svc RoomServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	roomServiceCreateHandler := connect_go.NewUnaryHandler(
		RoomServiceCreateProcedure,
		svc.Create,
		opts...,
	)
	return "/api.proto.v2.RoomService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RoomServiceCreateProcedure:
			roomServiceCreateHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRoomServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRoomServiceHandler struct{}

func (UnimplementedRoomServiceHandler) Create(context.Context, *connect_go.Request[v2.RoomServiceCreateRequest]) (*connect_go.Response[v2.RoomServiceCreateResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("api.proto.v2.RoomService.Create is not implemented"))
}
