// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/proto/v2/stream.proto

package protov2connect

import (
	context "context"
	errors "errors"
	v2 "github.com/21hack02win/nascalay-v2-backend/pkg/bufgen/api/proto/v2"
	connect_go "github.com/bufbuild/connect-go"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// StreamServiceName is the fully-qualified name of the StreamService service.
	StreamServiceName = "api.proto.v2.StreamService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// StreamServiceStreamProcedure is the fully-qualified name of the StreamService's Stream RPC.
	StreamServiceStreamProcedure = "/api.proto.v2.StreamService/Stream"
)

// StreamServiceClient is a client for the api.proto.v2.StreamService service.
type StreamServiceClient interface {
	Stream(context.Context) *connect_go.BidiStreamForClient[v2.StreamRequest, v2.StreamResponse]
}

// NewStreamServiceClient constructs a client for the api.proto.v2.StreamService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewStreamServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) StreamServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &streamServiceClient{
		stream: connect_go.NewClient[v2.StreamRequest, v2.StreamResponse](
			httpClient,
			baseURL+StreamServiceStreamProcedure,
			opts...,
		),
	}
}

// streamServiceClient implements StreamServiceClient.
type streamServiceClient struct {
	stream *connect_go.Client[v2.StreamRequest, v2.StreamResponse]
}

// Stream calls api.proto.v2.StreamService.Stream.
func (c *streamServiceClient) Stream(ctx context.Context) *connect_go.BidiStreamForClient[v2.StreamRequest, v2.StreamResponse] {
	return c.stream.CallBidiStream(ctx)
}

// StreamServiceHandler is an implementation of the api.proto.v2.StreamService service.
type StreamServiceHandler interface {
	Stream(context.Context, *connect_go.BidiStream[v2.StreamRequest, v2.StreamResponse]) error
}

// NewStreamServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewStreamServiceHandler(svc StreamServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	mux := http.NewServeMux()
	mux.Handle(StreamServiceStreamProcedure, connect_go.NewBidiStreamHandler(
		StreamServiceStreamProcedure,
		svc.Stream,
		opts...,
	))
	return "/api.proto.v2.StreamService/", mux
}

// UnimplementedStreamServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedStreamServiceHandler struct{}

func (UnimplementedStreamServiceHandler) Stream(context.Context, *connect_go.BidiStream[v2.StreamRequest, v2.StreamResponse]) error {
	return connect_go.NewError(connect_go.CodeUnimplemented, errors.New("api.proto.v2.StreamService.Stream is not implemented"))
}
